Branch1
dessany2p/MySolutions pull request #1
Opened 2023-01-26 17:40 UTC by dessany2p

2023-01-27 11:37 UTC, Deadlift3008 requested changes

2023-01-27 11:37 UTC, Deadlift3008 commented on solution.js
> +    x = a.slice(b) !== ending;
Здесь по логике не нужно больше проверок, можно вернуть `true`. Так как пустая строка будет всегда в каком-то смысле

2023-01-27 11:37 UTC, Deadlift3008 commented on solution.js
> +  return x;
Здесь последние 4 строки можно переписать тернарником в одну: 
`return ending === "" ? true : str.slice(-endingLength) === ending`

2023-01-30 10:03 UTC, Deadlift3008 commented on solution.js
> +  let x = str.slice(-endLength) === ending;
У тебя переменная `x` дальше нигде не используется, эту строку можно удалить вообще

2023-01-30 10:10 UTC, dessany2p commented on solution.js
> +  let x = str.slice(-endLength) === ending;
Решено

2023-01-30 10:11 UTC, Deadlift3008 approved these changes

2023-01-30 10:30 UTC, merged